# Generated by Django 3.2.4 on 2021-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdetail_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='event_image',
            field=models.ImageField(upload_to='events'),
        ),
    ]
