# Generated by Django 3.2.4 on 2021-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
